package org.zjy.blog.entity;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ARTICLE_ID
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.PUBLIC_TIME
     *
     * @mbg.generated
     */
    private Long publicTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.HEAT
     *
     * @mbg.generated
     */
    private Double heat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.COMMEND_NUM
     *
     * @mbg.generated
     */
    private Integer commendNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.READ_NUM
     *
     * @mbg.generated
     */
    private Integer readNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.DIGEST
     *
     * @mbg.generated
     */
    private String digest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ARTICLE_ID
     *
     * @return the value of article.ARTICLE_ID
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ARTICLE_ID
     *
     * @param articleId the value for article.ARTICLE_ID
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.PUBLIC_TIME
     *
     * @return the value of article.PUBLIC_TIME
     *
     * @mbg.generated
     */
    public Long getPublicTime() {
        return publicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.PUBLIC_TIME
     *
     * @param publicTime the value for article.PUBLIC_TIME
     *
     * @mbg.generated
     */
    public void setPublicTime(Long publicTime) {
        this.publicTime = publicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.HEAT
     *
     * @return the value of article.HEAT
     *
     * @mbg.generated
     */
    public Double getHeat() {
        return heat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.HEAT
     *
     * @param heat the value for article.HEAT
     *
     * @mbg.generated
     */
    public void setHeat(Double heat) {
        this.heat = heat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.COMMEND_NUM
     *
     * @return the value of article.COMMEND_NUM
     *
     * @mbg.generated
     */
    public Integer getCommendNum() {
        return commendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.COMMEND_NUM
     *
     * @param commendNum the value for article.COMMEND_NUM
     *
     * @mbg.generated
     */
    public void setCommendNum(Integer commendNum) {
        this.commendNum = commendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.READ_NUM
     *
     * @return the value of article.READ_NUM
     *
     * @mbg.generated
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.READ_NUM
     *
     * @param readNum the value for article.READ_NUM
     *
     * @mbg.generated
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.TITLE
     *
     * @return the value of article.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.TITLE
     *
     * @param title the value for article.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.DIGEST
     *
     * @return the value of article.DIGEST
     *
     * @mbg.generated
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.DIGEST
     *
     * @param digest the value for article.DIGEST
     *
     * @mbg.generated
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.CONTENT
     *
     * @return the value of article.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.CONTENT
     *
     * @param content the value for article.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}