package org.zjy.blog.entity;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_ID
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_TIME
     *
     * @mbg.generated
     */
    private Double commentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_NUM
     *
     * @mbg.generated
     */
    private Integer commentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_NAME
     *
     * @mbg.generated
     */
    private String commentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ARTICLE_ID
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_ID
     *
     * @return the value of comment.COMMENT_ID
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_ID
     *
     * @param commentId the value for comment.COMMENT_ID
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_TIME
     *
     * @return the value of comment.COMMENT_TIME
     *
     * @mbg.generated
     */
    public Double getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_TIME
     *
     * @param commentTime the value for comment.COMMENT_TIME
     *
     * @mbg.generated
     */
    public void setCommentTime(Double commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_NUM
     *
     * @return the value of comment.COMMENT_NUM
     *
     * @mbg.generated
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_NUM
     *
     * @param commentNum the value for comment.COMMENT_NUM
     *
     * @mbg.generated
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_NAME
     *
     * @return the value of comment.COMMENT_NAME
     *
     * @mbg.generated
     */
    public String getCommentName() {
        return commentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_NAME
     *
     * @param commentName the value for comment.COMMENT_NAME
     *
     * @mbg.generated
     */
    public void setCommentName(String commentName) {
        this.commentName = commentName == null ? null : commentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.EMAIL
     *
     * @return the value of comment.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.EMAIL
     *
     * @param email the value for comment.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ARTICLE_ID
     *
     * @return the value of comment.ARTICLE_ID
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ARTICLE_ID
     *
     * @param articleId the value for comment.ARTICLE_ID
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.CONTENT
     *
     * @return the value of comment.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.CONTENT
     *
     * @param content the value for comment.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}